config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do

  resources :articles do
    resources :comments
  end

  root 'pages#home'
  get 'about' => 'pages#about'
  get 'signup' => 'users#new' 
  get 'login' => 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'search' => 'search#search'

  resources :categories, except: [:destroy]

  resources :users, except: [:new] do 
      member do 
        get :articles
        get :following, :followers       
      end 
  end

  resources :relationships,       only: [:create, :destroy]

  mount Sidekiq::Web => '/sidekiq'

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

	def search
	  query = params[:q].presence && params[:q] 
	  if query 
	  	@articles = Article.search_published(query)
	  end
	end

end

app/views/search/search.html.erb
<h1 class= "text-center mt-4"> Elastic search for articles</h1>

<% unless @articles.nil? %>
  <% if @articles.empty? %>
    <h2 class="text-center mt-4 text-info">No articles found matching your query.</h2>
  <% else %>
   <div class="container">
    <%  @articles.each do |article| %>
      <div class="row justify-content-md-center">
        <div class="col-8 mt-4">
          <div class="card text-center shadow mb-5 bg-white rounded">
            <div class="card-header fst-italic">
              <% if article.user %>
                by <%= link_to article.user.username, user_path(article.user_id)  %>
              <% end %>
            </div>
            <div class="card-body">
              <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
              <p class="card-text text-start"><%= truncate(article.description, length: 100) %></p>
              <%= link_to "View", article_path(article.id), class: "btn btn-outline-success"%>
              <% if logged_in? && (article.user == current_user || current_user.admin?)%>
                <%= link_to "Edit", edit_article_path(article.id), class: "btn btn-outline-primary"%>
                <%= link_to "Delete", article_path(article.id), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger"%>
              <% end %>
            </div>
            <div class="card-footer text-muted">
              <small>created <%= time_ago_in_words(article.created_at)%> ago, edited <%= time_ago_in_words(article.updated_at) %> ago</small> 
            </div>
          </div>
        </div>
    </div>
  <% end %>
</div>
  <% end %>
<% end %>