config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do

  resources :articles do
    resources :comments
  end

  root 'pages#home'
  get 'about' => 'pages#about'
  get 'signup' => 'users#new' 
  get 'login' => 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'search' => 'search#search'

  resources :categories, except: [:destroy]

  resources :users, except: [:new] do 
      member do 
        get :articles
        get :following, :followers       
      end 
  end

  resources :relationships,       only: [:create, :destroy]

  mount Sidekiq::Web => '/sidekiq'

end

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger d-flex align-items-center alert-dismissible fade show" role="alert">
  	<div>
<!-- 	    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
 -->	    <h4 class="alert-heading"><%= t 'global.forms.messages.errors', count: obj.errors.count, op: obj.class.name.downcase %></h4>
	    <ul>
	      <% obj.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	    </ul>
	    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  </div>
<% end %>




			

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="mb-3">
  <div>
  <a href="<%= following_user_path(@user) %>">
    <strong id="following">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  </div>
  <div>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
  </div>
</div>