config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do

  resources :articles do
    resources :comments
  end

  root 'pages#home'
  get 'about' => 'pages#about'
  get 'signup' => 'users#new' 
  get 'login' => 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'search' => 'search#search'

  resources :categories, except: [:destroy]

  resources :users, except: [:new] do 
      member do 
        get :articles
        get :following, :followers       
      end 
  end

  resources :relationships,       only: [:create, :destroy]

  mount Sidekiq::Web => '/sidekiq'

end

app/models/category.rb
class Category < ActiveRecord::Base
	validates :name, presence: true, length: {maximum: 25, minimum: 3}
	validates_uniqueness_of :name

	has_many :article_categories
	has_many :articles, through: :article_categories

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	before_action :require_admin_user, except: [:show,:index]
  before_action :set_category, only: [:show, :edit, :update] 


	
	def new
		@category = Category.new
	end


	def create
		@category = Category.new(category_params)
		if @category.save
			flash[:notice] = "Category was successfully created"
			redirect_to @category
		else
			render 'new'
		end
	end

	def index
		@categories = Category.all
	end

	def show	
		@articles = @category.articles
	end

	def edit
	end

	def update
		if @category.update(category_params)
			flash[:notice] = "Category updated successfully"
			redirect_to @category
		else
			render 'edit'
		end
	end


	private

	def category_params
		params.require(:category).permit(:name)
	end

	def require_admin_user
		if !(logged_in? && current_user.admin?)
			flash[:alert] = "Only admins can perform this action"
			redirect_to categories_path
		end
	end

	def set_category
		@category = Category.find_by_id(params[:id])
	end


end

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category),class: "badge rounded-pill bg-info me-1 text-decoration-none" %>

app/views/categories/_form.html.erb
<div class="col-10">
	<%= render 'shared/errors', obj: @category %>
	<%= form_for @category, html: {class: "shadow p-3 mb-3 bg-info rounded"} do |form| %>	
		<div class="form-group row mb-3">		
			<%= form.label :name, "Category name",  class: "col-2 col-form-label text-light"%>	
			<div class="col-10">			
				<%= form.text_field :name,  class: "form-control shadow rounded", placeholder: "Enter a name"%>
			</div>
		</div>

		<div class="form-group text-center">
			<%= form.submit class: "btn btn-outline-light btn-lg" %>
		</div>
	<% end %>
</div>	

app/views/categories/edit.html.erb
<h1 class= "text-center mt-4"> Edit category</h1>
<div class="container">
	<div class="row justify-content-center">
			<%= render 'form' %>	
			<%= link_to '[ Cancel & Return to category ]' , category_path(@category), class: "text-info text-center" %>
	</div>		
</div>

app/views/categories/index.html.erb
<h1 class= "text-center mt-4"> Categories</h1>
<div class="container">
    <%  @categories.each do |category| %>
      <div class="row justify-content-md-center">
        <div class="col-4 mt-4">
          <div class="card text-center shadow mb-5 bg-white rounded">
            <div class="card-body">
              <h5 class="card-title"><%= link_to category.name, category_path(category), class: "text-success link-custom-style" %></h5>
              <p class="card-title"><%= pluralize(category.articles.count,'article') %></p>
            </div>
            <div class="card-footer text-muted">
              <small>created <%= time_ago_in_words(category.created_at)%> ago, edited <%= time_ago_in_words(category.updated_at) %> ago</small> 
            </div>
          </div>
        </div>
      </div>
    <% end %>
</div>



    

app/views/categories/new.html.erb
<h1 class= "text-center mt-4"> Create a new category</h1>
<div class="container">
	<div class="row justify-content-center">
			<%= render 'form' %>	
			<%= link_to '[ Cancel & Return to categories listing ]' , categories_path, class: "text-info text-center" %>
	</div>		
</div>

app/views/categories/show.html.erb
<h1 class= "text-center mt-4"> Category: <%= @category.name %></h1>
<% if logged_in? && current_user.admin? %>
  <div class="text-center mt-4">
    <%= link_to "Edit category", edit_category_path(@category), class: "btn btn-outline-primary" %>
  </div>
<% end %>
<h3 class= "text-center mt-4"> Articles </h3>
<%= render 'articles/article' %>