config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do

  resources :articles do
    resources :comments
  end

  root 'pages#home'
  get 'about' => 'pages#about'
  get 'signup' => 'users#new' 
  get 'login' => 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'search' => 'search#search'

  resources :categories, except: [:destroy]

  resources :users, except: [:new] do 
      member do 
        get :articles
        get :following, :followers       
      end 
  end

  resources :relationships,       only: [:create, :destroy]

  mount Sidekiq::Web => '/sidekiq'

end

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="flex-shrink-0 py-4 bg-dark text-white">
	<div class="container text-center">
	  <small>Copyright &copy; <%= link_to "Sravan Perumandla", "https://sravanperumandla.com" , class: "text-white" %></small>
	</div>
</footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand", id: "logo" %> 
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
	  <ul class="navbar-nav me-auto mb-2 mb-lg-0">
	    <li class="nav-item">
	      <%= link_to t('global.home.nav.bloggers'), users_path, class: "nav-link" %>
	    </li>
	    <li class="nav-item dropdown">
	      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
	        <%= t('global.home.nav.articles') %>
	      </a>
	      <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
	      	<% if logged_in? %>
		        <li><%= link_to t('global.home.nav.create_new_article'), new_article_path, class: "dropdown-item" %> </li>
	        <% end %>
	        <li><%= link_to t('global.home.nav.view_articles'), articles_path, class: "dropdown-item" %> </li>
	      </ul>
	    </li>
	    <li class="nav-item dropdown">
	      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
	        <%= t('global.home.nav.category') %>
	      </a>
	      <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
	      	<% if logged_in? && current_user.admin? %>
		        <li><%= link_to t('global.home.nav.create_new_category'), new_category_path, class: "dropdown-item" %> </li>
	        <% end %>
	        <li><%= link_to t('global.home.nav.view_categories'), categories_path, class: "dropdown-item" %> </li>
	      </ul>
	    </li>

	    <% if logged_in? %>
		    <li class="nav-item dropdown">
		      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
		        <%= 'Admin' if current_user.admin? %> Profile [<%= current_user.username %>]
		      </a>
		      <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
		        <li><%= link_to "View your profile", user_path(current_user), class: "dropdown-item" %> </li>
		        <li><%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %> </li>
		        <li><%= link_to "Delete profile", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data:{confirm: "Are you sure?"} %> </li>
		      </ul>
		    </li>
	    <% end %>
	    <% if logged_in? %>
		     <li class="nav-item">
		      <%= link_to t('global.home.nav.logout'), logout_path, class: "nav-link", method: :delete %>
		    </li>
	    <% else %>
		    <li class="nav-item">
		      <%= link_to t('global.home.nav.login'), login_path, class: "nav-link" %>
		    </li>
		    <li class="nav-item">
		      <%= link_to t('global.home.nav.signup'), signup_path, class: "nav-link" %>
		    </li>   	
	    <% end %>
	  </ul>
	  <form class="d-flex" action="/search">
	  	 <input class="form-control me-2" name="q" type="text" placeholder="Search" aria-label="Search"> 
	  	  <button class="btn btn-outline-success" type="submit"><%= t('global.home.nav.search')%></button>
	  </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="d-flex flex-column">
  <%= render 'layouts/navigation' %>
  <div class="container">
    <% flash.each do |name, msg| -%>
      <div class="alert alert-success d-flex align-items-center alert-dismissible fade show" role="alert">
        <%= content_tag :div, msg, class: name %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end -%>
  </div>
  <div id="page-content">
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>